#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyTrap.Droid.Resource", IsApplication=true)]

namespace MyTrap.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::MyTrap.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MyTrap.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MyTrap.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::MyTrap.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::MyTrap.Droid.Resource.String.Hello;
			global::Xamarin.InAppBilling.Resource.String.library_name = global::MyTrap.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int com_facebook_auxiliary_view_position = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int com_facebook_confirm_logout = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int com_facebook_foreground_color = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int com_facebook_horizontal_alignment = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int com_facebook_is_cropped = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int com_facebook_login_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int com_facebook_logout_text = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int com_facebook_object_id = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int com_facebook_object_type = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int com_facebook_preset_size = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int com_facebook_style = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int com_facebook_tooltip_mode = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_button_background_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_button_background_color_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_button_background_color_pressed = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_button_like_background_color_selected = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_button_login_silver_background_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_button_login_silver_background_color_pressed = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_button_send_background_color = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_button_send_background_color_pressed = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_likeboxcountview_border_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_likeboxcountview_text_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_likeview_text_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_share_button_text_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int hockeyapp_background_header = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hockeyapp_background_light = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hockeyapp_background_white = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int hockeyapp_button_background = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int hockeyapp_button_background_pressed = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int hockeyapp_button_background_selected = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hockeyapp_text_black = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hockeyapp_text_light = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int hockeyapp_text_normal = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int hockeyapp_text_white = 2131034134;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060013
			public const int activity_horizontal_margin = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int activity_vertical_margin = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_likeboxcountview_border_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_likeboxcountview_border_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_likeboxcountview_caret_height = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_likeboxcountview_caret_width = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_likeboxcountview_text_padding = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_likeboxcountview_text_size = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_likeview_edge_padding = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_likeview_internal_padding = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_likeview_text_size = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_profilepictureview_preset_size_large = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_share_button_padding_bottom = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_share_button_padding_left = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_share_button_padding_right = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_share_button_padding_top = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_share_button_text_size = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_tooltip_horizontal_padding = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int navigation_drawer_width = 2131099669;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_info_profile = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_mytrap = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_top_notification = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_top_profile = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_buy_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_border = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buy128x128 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_like_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_like_icon_selected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_button_login_silver_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_send_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_button_send_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_close = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_profile_picture_blank_portrait = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_profile_picture_blank_square = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_black_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_tooltip_black_bottomnub = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_tooltip_black_topnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_tooltip_black_xout = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_tooltip_blue_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_tooltip_blue_bottomnub = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_tooltip_blue_topnub = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_tooltip_blue_xout = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int drawer_shadow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int hockeyapp_btn_background = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_launcher = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon_trap_map = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int logo_big = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int logo_small = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int messenger_bubble_large_blue = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int messenger_bubble_large_white = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int messenger_bubble_small_blue = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int messenger_bubble_small_white = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int messenger_button_blue_bg_round = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int messenger_button_blue_bg_selector = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int messenger_button_send_round_shadow = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int messenger_button_white_bg_round = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int messenger_button_white_bg_selector = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int profile_picture_background = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int side_menu = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int splash = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int trap_bear_trap_icon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int trap_bear_trap_selected_icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int trap_dogs_trap_icon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int trap_dogs_trap_selected_icon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int trap_mine_trap_icon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int trap_mine_trap_selected_icon = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int trap_pit_trap_icon = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int trap_pit_trap_selected_icon = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int user_empty = 2130837555;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int actionBarLogo = 2131230738;
			
			// aapt resource value: 0x7f08000c
			public const int automatic = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int bottom = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int box_count = 2131230723;
			
			// aapt resource value: 0x7f080023
			public const int btn_arm_trap = 2131230755;
			
			// aapt resource value: 0x7f08002f
			public const int btn_home_arm = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int btn_home_buy = 2131230768;
			
			// aapt resource value: 0x7f080017
			public const int btn_login_facebook = 2131230743;
			
			// aapt resource value: 0x7f08005c
			public const int btn_trap_item_buy = 2131230812;
			
			// aapt resource value: 0x7f080004
			public const int button = 2131230724;
			
			// aapt resource value: 0x7f080046
			public const int button_add_response = 2131230790;
			
			// aapt resource value: 0x7f080041
			public const int button_attachment = 2131230785;
			
			// aapt resource value: 0x7f08004b
			public const int button_login = 2131230795;
			
			// aapt resource value: 0x7f080047
			public const int button_refresh = 2131230791;
			
			// aapt resource value: 0x7f080042
			public const int button_send = 2131230786;
			
			// aapt resource value: 0x7f08004f
			public const int button_update = 2131230799;
			
			// aapt resource value: 0x7f080009
			public const int center = 2131230729;
			
			// aapt resource value: 0x7f08001b
			public const int com_facebook_body_frame = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int com_facebook_button_xout = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int com_facebook_fragment_container = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int com_facebook_login_activity_progress_bar = 2131230746;
			
			// aapt resource value: 0x7f08001f
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int com_facebook_tooltip_bubble_view_text_body = 2131230750;
			
			// aapt resource value: 0x7f08001c
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131230748;
			
			// aapt resource value: 0x7f080014
			public const int container = 2131230740;
			
			// aapt resource value: 0x7f08000d
			public const int display_always = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int drawer_layout = 2131230739;
			
			// aapt resource value: 0x7f080021
			public const int group_arm_choose_traps = 2131230753;
			
			// aapt resource value: 0x7f080059
			public const int group_info_item_buy = 2131230809;
			
			// aapt resource value: 0x7f080034
			public const int group_my_traps = 2131230772;
			
			// aapt resource value: 0x7f080035
			public const int group_top_notification = 2131230773;
			
			// aapt resource value: 0x7f080025
			public const int group_top_profile = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int img_home_profile = 2131230758;
			
			// aapt resource value: 0x7f080016
			public const int img_logo_login = 2131230742;
			
			// aapt resource value: 0x7f080056
			public const int img_my_trap = 2131230806;
			
			// aapt resource value: 0x7f080036
			public const int img_notification_other_user = 2131230774;
			
			// aapt resource value: 0x7f080058
			public const int img_trap_item_buy = 2131230808;
			
			// aapt resource value: 0x7f080007
			public const int inline = 2131230727;
			
			// aapt resource value: 0x7f08003d
			public const int input_email = 2131230781;
			
			// aapt resource value: 0x7f08003f
			public const int input_message = 2131230783;
			
			// aapt resource value: 0x7f08003c
			public const int input_name = 2131230780;
			
			// aapt resource value: 0x7f08004a
			public const int input_password = 2131230794;
			
			// aapt resource value: 0x7f08003e
			public const int input_subject = 2131230782;
			
			// aapt resource value: 0x7f080051
			public const int label_author = 2131230801;
			
			// aapt resource value: 0x7f080052
			public const int label_date = 2131230802;
			
			// aapt resource value: 0x7f080044
			public const int label_last_updated = 2131230788;
			
			// aapt resource value: 0x7f080039
			public const int label_message = 2131230777;
			
			// aapt resource value: 0x7f080053
			public const int label_text = 2131230803;
			
			// aapt resource value: 0x7f08004d
			public const int label_title = 2131230797;
			
			// aapt resource value: 0x7f08004e
			public const int label_version = 2131230798;
			
			// aapt resource value: 0x7f08000f
			public const int large = 2131230735;
			
			// aapt resource value: 0x7f080028
			public const int layout_home_points = 2131230760;
			
			// aapt resource value: 0x7f08002b
			public const int layout_home_traps = 2131230763;
			
			// aapt resource value: 0x7f080027
			public const int lbl_home_name = 2131230759;
			
			// aapt resource value: 0x7f08002e
			public const int lbl_home_other_msg = 2131230766;
			
			// aapt resource value: 0x7f080029
			public const int lbl_home_points = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int lbl_home_points_value = 2131230762;
			
			// aapt resource value: 0x7f08002c
			public const int lbl_home_traps = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int lbl_home_traps_value = 2131230765;
			
			// aapt resource value: 0x7f080037
			public const int lbl_notification_msg = 2131230775;
			
			// aapt resource value: 0x7f080057
			public const int lbl_qtd_my_trap = 2131230807;
			
			// aapt resource value: 0x7f080033
			public const int lbl_title_my_traps = 2131230771;
			
			// aapt resource value: 0x7f080031
			public const int lbl_title_shop_buy = 2131230769;
			
			// aapt resource value: 0x7f08000a
			public const int left = 2131230730;
			
			// aapt resource value: 0x7f080054
			public const int list_attachments = 2131230804;
			
			// aapt resource value: 0x7f080048
			public const int list_feedback_messages = 2131230792;
			
			// aapt resource value: 0x7f080032
			public const int list_traps_to_buy = 2131230770;
			
			// aapt resource value: 0x7f080022
			public const int map_arm = 2131230754;
			
			// aapt resource value: 0x7f080038
			public const int map_notification = 2131230776;
			
			// aapt resource value: 0x7f080024
			public const int map_traps_armed = 2131230756;
			
			// aapt resource value: 0x7f080055
			public const int messenger_send_button = 2131230805;
			
			// aapt resource value: 0x7f080015
			public const int navigation_drawer = 2131230741;
			
			// aapt resource value: 0x7f08000e
			public const int never_display = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int normal = 2131230736;
			
			// aapt resource value: 0x7f080000
			public const int open_graph = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int page = 2131230721;
			
			// aapt resource value: 0x7f080018
			public const int progress_bar_login = 2131230744;
			
			// aapt resource value: 0x7f08000b
			public const int right = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int small = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int standard = 2131230725;
			
			// aapt resource value: 0x7f080049
			public const int text_headline = 2131230793;
			
			// aapt resource value: 0x7f080008
			public const int top = 2131230728;
			
			// aapt resource value: 0x7f08005a
			public const int txt_qty_item_buy = 2131230810;
			
			// aapt resource value: 0x7f080020
			public const int txt_title_arm = 2131230752;
			
			// aapt resource value: 0x7f08005b
			public const int txt_value_item_buy = 2131230811;
			
			// aapt resource value: 0x7f080002
			public const int unknown = 2131230722;
			
			// aapt resource value: 0x7f08004c
			public const int view_header = 2131230796;
			
			// aapt resource value: 0x7f080050
			public const int web_update_details = 2131230800;
			
			// aapt resource value: 0x7f080040
			public const int wrapper_attachments = 2131230784;
			
			// aapt resource value: 0x7f08003b
			public const int wrapper_feedback = 2131230779;
			
			// aapt resource value: 0x7f08003a
			public const int wrapper_feedback_scroll = 2131230778;
			
			// aapt resource value: 0x7f080043
			public const int wrapper_messages = 2131230787;
			
			// aapt resource value: 0x7f080045
			public const int wrapper_messages_buttons = 2131230789;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_splash = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_activity_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_login_fragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_tooltip_bubble = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_arm = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_armed_traps = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fragment_home = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fragment_navigation_drawer = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fragment_shop = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int fragment_trap_notification = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int hockeyapp_activity_expiry_info = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int hockeyapp_activity_feedback = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int hockeyapp_activity_login = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int hockeyapp_activity_update = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int hockeyapp_fragment_update = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int hockeyapp_view_feedback_message = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int menu_global = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int messenger_button_send_blue_large = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int messenger_button_send_blue_round = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int messenger_button_send_blue_small = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int messenger_button_send_white_large = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int messenger_button_send_white_round = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int messenger_button_send_white_small = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int my_trap_template = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int trap_to_buy_list_item = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040080
			public const int BIG = 2130968704;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f04007f
			public const int NORMAL = 2130968703;
			
			// aapt resource value: 0x7f04007e
			public const int SMALL = 2130968702;
			
			// aapt resource value: 0x7f040075
			public const int action_settings = 2130968693;
			
			// aapt resource value: 0x7f040061
			public const int alert_title_error = 2130968673;
			
			// aapt resource value: 0x7f040060
			public const int alert_title_success = 2130968672;
			
			// aapt resource value: 0x7f04005b
			public const int app_name = 2130968667;
			
			// aapt resource value: 0x7f040069
			public const int arm_a_trap_msg = 2130968681;
			
			// aapt resource value: 0x7f040070
			public const int arm_left_menu = 2130968688;
			
			// aapt resource value: 0x7f040067
			public const int arm_more = 2130968679;
			
			// aapt resource value: 0x7f040078
			public const int arm_trap_title_alert = 2130968696;
			
			// aapt resource value: 0x7f04007d
			public const int arming_trap = 2130968701;
			
			// aapt resource value: 0x7f04008b
			public const int attention = 2130968715;
			
			// aapt resource value: 0x7f040062
			public const int btn_arm_trap = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int btn_buy_trap = 2130968675;
			
			// aapt resource value: 0x7f040083
			public const int buy = 2130968707;
			
			// aapt resource value: 0x7f04006a
			public const int buy_a_trap_msg = 2130968682;
			
			// aapt resource value: 0x7f040068
			public const int buy_more = 2130968680;
			
			// aapt resource value: 0x7f04007b
			public const int choose_your_trap = 2130968699;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_image_download_unknown_error = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int com_facebook_internet_permission_error_message = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_facebook_internet_permission_error_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_facebook_like_button_liked = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int com_facebook_like_button_not_liked = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_loading = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_loginview_cancel_action = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_loginview_log_in_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_loginview_log_in_button_long = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_loginview_log_out_action = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_loginview_log_out_button = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_loginview_logged_in_as = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int com_facebook_loginview_logged_in_using_facebook = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int com_facebook_send_button_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int com_facebook_share_button_text = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int com_facebook_tooltip_default = 2130968594;
			
			// aapt resource value: 0x7f04005f
			public const int error_login_facebook = 2130968671;
			
			// aapt resource value: 0x7f04006d
			public const int facebook_app_id = 2130968685;
			
			// aapt resource value: 0x7f04008d
			public const int format_date_hour_minute = 2130968717;
			
			// aapt resource value: 0x7f04008c
			public const int general_error = 2130968716;
			
			// aapt resource value: 0x7f04007c
			public const int getting_target = 2130968700;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_crash_dialog_message = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_crash_dialog_negative_button = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_crash_dialog_neutral_button = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_crash_dialog_positive_button = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_crash_dialog_title = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_dialog_error_message = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_dialog_error_title = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_dialog_negative_button = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_dialog_positive_button = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_download_failed_dialog_message = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_download_failed_dialog_title = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_error_no_network_message = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_expiry_info_text = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_expiry_info_title = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_attach_file = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_attach_picture = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_attachment_button_text = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_attachment_error = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_attachment_loading = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_email_hint = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_failed_text = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_feedback_failed_title = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_feedback_fetching_feedback_text = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_feedback_generic_error = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_feedback_last_updated_text = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_feedback_message_hint = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_feedback_name_hint = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_feedback_refresh_button_text = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_feedback_response_button_text = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_feedback_select_file = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_feedback_select_picture = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_feedback_send_button_text = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_feedback_send_generic_error = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_feedback_send_network_error = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_feedback_sending_feedback_text = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_feedback_subject_hint = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_feedback_title = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_feedback_validate_email_empty = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_feedback_validate_email_error = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_feedback_validate_name_error = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_feedback_validate_subject_error = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_feedback_validate_text_error = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_login_email_hint = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int hockeyapp_login_headline_text = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int hockeyapp_login_headline_text_email_only = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int hockeyapp_login_login_button_text = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int hockeyapp_login_missing_credentials_toast = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int hockeyapp_login_password_hint = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int hockeyapp_paint_dialog_message = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int hockeyapp_paint_dialog_negative_button = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int hockeyapp_paint_dialog_neutral_button = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int hockeyapp_paint_dialog_positive_button = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int hockeyapp_paint_indicator_toast = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int hockeyapp_paint_menu_clear = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int hockeyapp_paint_menu_save = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int hockeyapp_paint_menu_undo = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int hockeyapp_permission_dialog_negative_button = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int hockeyapp_permission_dialog_positive_button = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int hockeyapp_permission_update_message = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int hockeyapp_permission_update_title = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int hockeyapp_update_button = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int hockeyapp_update_dialog_message = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int hockeyapp_update_dialog_negative_button = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int hockeyapp_update_dialog_positive_button = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int hockeyapp_update_dialog_title = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int hockeyapp_update_mandatory_toast = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int hockeyapp_update_version_details_label = 2130968666;
			
			// aapt resource value: 0x7f04006f
			public const int home_left_menu = 2130968687;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04008e
			public const int loading = 2130968718;
			
			// aapt resource value: 0x7f040084
			public const int loading_inventory = 2130968708;
			
			// aapt resource value: 0x7f040087
			public const int loading_traps = 2130968711;
			
			// aapt resource value: 0x7f04005e
			public const int login_with_email = 2130968670;
			
			// aapt resource value: 0x7f04005c
			public const int login_with_facebook = 2130968668;
			
			// aapt resource value: 0x7f040013
			public const int messenger_send_button_text = 2130968595;
			
			// aapt resource value: 0x7f040079
			public const int msg_confirm_arm_trap = 2130968697;
			
			// aapt resource value: 0x7f04007a
			public const int msg_success_arm_trap = 2130968698;
			
			// aapt resource value: 0x7f040082
			public const int my_traps = 2130968706;
			
			// aapt resource value: 0x7f040074
			public const int navigation_drawer_close = 2130968692;
			
			// aapt resource value: 0x7f040073
			public const int navigation_drawer_open = 2130968691;
			
			// aapt resource value: 0x7f040064
			public const int new_trap_notification = 2130968676;
			
			// aapt resource value: 0x7f040089
			public const int no = 2130968713;
			
			// aapt resource value: 0x7f040086
			public const int no_traps_armed = 2130968710;
			
			// aapt resource value: 0x7f04008a
			public const int ok = 2130968714;
			
			// aapt resource value: 0x7f04006b
			public const int points = 2130968683;
			
			// aapt resource value: 0x7f040085
			public const int registering_purchase = 2130968709;
			
			// aapt resource value: 0x7f040071
			public const int shop_left_menu = 2130968689;
			
			// aapt resource value: 0x7f040081
			public const int store = 2130968705;
			
			// aapt resource value: 0x7f040076
			public const int title_activity_arm_fragment = 2130968694;
			
			// aapt resource value: 0x7f04006e
			public const int title_activity_home = 2130968686;
			
			// aapt resource value: 0x7f040077
			public const int title_activity_profile_fragment = 2130968695;
			
			// aapt resource value: 0x7f04005d
			public const int title_login = 2130968669;
			
			// aapt resource value: 0x7f04006c
			public const int traps = 2130968684;
			
			// aapt resource value: 0x7f040072
			public const int traps_armed_left_menu = 2130968690;
			
			// aapt resource value: 0x7f040088
			public const int yes = 2130968712;
			
			// aapt resource value: 0x7f040065
			public const int you_caught_by_user = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int you_caught_other_user = 2130968678;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070015
			public const int HockeyApp_ButtonStyle = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int HockeyApp_EditTextStyle = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int HockeyApp_SingleLineInputStyle = 2131165207;
			
			// aapt resource value: 0x7f070000
			public const int MessengerButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MessengerButton_Blue = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MessengerButton_Blue_Large = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MessengerButton_Blue_Small = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MessengerButton_White = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int MessengerButton_White_Large = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int MessengerButton_White_Small = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int MessengerButtonText = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int MessengerButtonText_Blue = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int MessengerButtonText_Blue_Large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int MessengerButtonText_Blue_Small = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int MessengerButtonText_White = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int MessengerButtonText_White_Large = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int MessengerButtonText_White_Small = 2131165197;
			
			// aapt resource value: 0x7f070018
			public const int Theme_MyTrap = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int Theme_MyTrap_ActionBar = 2131165209;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_button = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_button_like = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_button_send = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_button_share = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_loginview_default_style = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_loginview_silver_style = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int tooltip_bubble_text = 2131165204;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_like_view = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
